version: "3"
services:
  arangodb:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8529:8529
    environment:
      - ARANGO_ROOT_PASSWORD=your-password
    volumes:
      - arangodb_data:/var/lib/arangodb3

volumes:
  arangodb_data: